//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDL.Front.TodoListService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TodoListService.ITodoListService")]
    public interface ITodoListService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/GetAllData", ReplyAction="http://tempuri.org/ITodoListService/GetAllDataResponse")]
        string GetAllData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/GetAllData", ReplyAction="http://tempuri.org/ITodoListService/GetAllDataResponse")]
        System.Threading.Tasks.Task<string> GetAllDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/AddNewItem", ReplyAction="http://tempuri.org/ITodoListService/AddNewItemResponse")]
        string AddNewItem(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/AddNewItem", ReplyAction="http://tempuri.org/ITodoListService/AddNewItemResponse")]
        System.Threading.Tasks.Task<string> AddNewItemAsync(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/RemoveData", ReplyAction="http://tempuri.org/ITodoListService/RemoveDataResponse")]
        string RemoveData(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/RemoveData", ReplyAction="http://tempuri.org/ITodoListService/RemoveDataResponse")]
        System.Threading.Tasks.Task<string> RemoveDataAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/ChangeStatus", ReplyAction="http://tempuri.org/ITodoListService/ChangeStatusResponse")]
        string ChangeStatus(System.Guid id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/ChangeStatus", ReplyAction="http://tempuri.org/ITodoListService/ChangeStatusResponse")]
        System.Threading.Tasks.Task<string> ChangeStatusAsync(System.Guid id, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITodoListServiceChannel : TDL.Front.TodoListService.ITodoListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TodoListServiceClient : System.ServiceModel.ClientBase<TDL.Front.TodoListService.ITodoListService>, TDL.Front.TodoListService.ITodoListService {
        
        public TodoListServiceClient() {
        }
        
        public TodoListServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TodoListServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoListServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoListServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllData() {
            return base.Channel.GetAllData();
        }
        
        public System.Threading.Tasks.Task<string> GetAllDataAsync() {
            return base.Channel.GetAllDataAsync();
        }
        
        public string AddNewItem(string description) {
            return base.Channel.AddNewItem(description);
        }
        
        public System.Threading.Tasks.Task<string> AddNewItemAsync(string description) {
            return base.Channel.AddNewItemAsync(description);
        }
        
        public string RemoveData(System.Guid id) {
            return base.Channel.RemoveData(id);
        }
        
        public System.Threading.Tasks.Task<string> RemoveDataAsync(System.Guid id) {
            return base.Channel.RemoveDataAsync(id);
        }
        
        public string ChangeStatus(System.Guid id, string status) {
            return base.Channel.ChangeStatus(id, status);
        }
        
        public System.Threading.Tasks.Task<string> ChangeStatusAsync(System.Guid id, string status) {
            return base.Channel.ChangeStatusAsync(id, status);
        }
    }
}
