//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDL.Front.TodoListService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TodoListService.ITodoListService")]
    public interface ITodoListService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/GetAllData", ReplyAction="http://tempuri.org/ITodoListService/GetAllDataResponse")]
        TDL.Services.Models.Response GetAllData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/GetAllData", ReplyAction="http://tempuri.org/ITodoListService/GetAllDataResponse")]
        System.Threading.Tasks.Task<TDL.Services.Models.Response> GetAllDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/AddNewItem", ReplyAction="http://tempuri.org/ITodoListService/AddNewItemResponse")]
        TDL.Services.Models.Response AddNewItem(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/AddNewItem", ReplyAction="http://tempuri.org/ITodoListService/AddNewItemResponse")]
        System.Threading.Tasks.Task<TDL.Services.Models.Response> AddNewItemAsync(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/RemoveData", ReplyAction="http://tempuri.org/ITodoListService/RemoveDataResponse")]
        TDL.Services.Models.Response RemoveData(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/RemoveData", ReplyAction="http://tempuri.org/ITodoListService/RemoveDataResponse")]
        System.Threading.Tasks.Task<TDL.Services.Models.Response> RemoveDataAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/ChangeStatus", ReplyAction="http://tempuri.org/ITodoListService/ChangeStatusResponse")]
        TDL.Services.Models.Response ChangeStatus(System.Guid id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/ChangeStatus", ReplyAction="http://tempuri.org/ITodoListService/ChangeStatusResponse")]
        System.Threading.Tasks.Task<TDL.Services.Models.Response> ChangeStatusAsync(System.Guid id, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITodoListServiceChannel : TDL.Front.TodoListService.ITodoListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TodoListServiceClient : System.ServiceModel.ClientBase<TDL.Front.TodoListService.ITodoListService>, TDL.Front.TodoListService.ITodoListService {
        
        public TodoListServiceClient() {
        }
        
        public TodoListServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TodoListServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoListServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoListServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TDL.Services.Models.Response GetAllData() {
            return base.Channel.GetAllData();
        }
        
        public System.Threading.Tasks.Task<TDL.Services.Models.Response> GetAllDataAsync() {
            return base.Channel.GetAllDataAsync();
        }
        
        public TDL.Services.Models.Response AddNewItem(string description) {
            return base.Channel.AddNewItem(description);
        }
        
        public System.Threading.Tasks.Task<TDL.Services.Models.Response> AddNewItemAsync(string description) {
            return base.Channel.AddNewItemAsync(description);
        }
        
        public TDL.Services.Models.Response RemoveData(System.Guid id) {
            return base.Channel.RemoveData(id);
        }
        
        public System.Threading.Tasks.Task<TDL.Services.Models.Response> RemoveDataAsync(System.Guid id) {
            return base.Channel.RemoveDataAsync(id);
        }
        
        public TDL.Services.Models.Response ChangeStatus(System.Guid id, string status) {
            return base.Channel.ChangeStatus(id, status);
        }
        
        public System.Threading.Tasks.Task<TDL.Services.Models.Response> ChangeStatusAsync(System.Guid id, string status) {
            return base.Channel.ChangeStatusAsync(id, status);
        }
    }
}
